# This is a basic workflow to help you get started with Actions

name: konnect

on:
  workflow_dispatch:
  
jobs:
  deploy_to_konnect:
    runs-on: ubuntu-latest
    name: Deploying Kong Configuration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Deck
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.34.0/deck_1.34.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          sudo cp /tmp/deck /usr/local/bin/
          deck version
          
      - name: Install Insomnia
        run: |
          wget https://github.com/Kong/insomnia/releases/download/lib%408.6.1/inso-linux-8.6.1.tar.xz
          tar -xf inso-linux-8.6.1.tar.xz 
          sudo cp inso /usr/local/bin/
          ls
          
      - name: Lint OAS spec
        run: ./inso lint spec ./kong-config/spec.yaml  

      - name: Generate new gateway configuration
        run: | 
         deck file openapi2kong --spec ./kong-config/spec.yaml --output-file kong.yaml 

      - name: Add Global plugins
        run:  cat kong.yaml | deck file add-plugins ./kong-config/global-plugin.yaml -o kong.yaml 

      - name: Add Route plugins
        run:  cat kong.yaml | deck file add-plugins ./kong-config/route-level-plugin.yaml -o kong.yaml 

      - name: Add Service plugins
        run:  cat kong.yaml | deck file add-plugins ./kong-config/service-level-plugin.yaml -o kong.yaml

      - name: Ping to Konnect Org
        run:  deck gateway ping --konnect-token $KONNECT_TOKEN 
        env: 
          KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
  
      - name: Backup existing configuration
        run:  deck gateway dump --konnect-token $KONNECT_TOKEN --konnect-control-plane-name $CP_NAME > kong-backup.yaml
        env: 
          KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
          CP_NAME: ${{ secrets.CP_NAME }}

      - name: Apply new configuration
        run: |
           deck gateway sync kong.yaml --konnect-token $KONNECT_TOKEN --konnect-control-plane-name $CP_NAME > kong-backup.yaml
           sleep 10
        env: 
          KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
          CP_NAME: ${{ secrets.CP_NAME }}       
          
        

        

